### ISSUE TITLE
update build process

### ISSUE THREAD

**Issue by ulfw** [jasonphillips/tinymce-word-paste-filter#5]
Could you please have look at the build process?
After cloning the repo, init submodule and running the build I got the following error:

Error: Could not resolve entry module (tinymce/modules/tinymce/lib/plugins/paste/main/ts/core/WordFilter)

FirstI think the directory structure is wrong, its now

tinymce/modules/tinymce/src/plugins/paste/main/ts/core/WordFilter

But the error still occurs after updateing the path.

thx

**Comment by jasonphillips** [comment]
closed in https://github.com/jasonphillips/tinymce-word-paste-filter/pull/12

**Comment by jasonphillips** [comment]
closed in https://github.com/jasonphillips/tinymce-word-paste-filter/pull/12
