### ISSUE TITLE
Switch to MIT license

### ISSUE THREAD

**Issue by baodoan** [jasonphillips/tinymce-word-paste-filter#8]
Thanks for building an awesome module @jasonphillips. We'd love to use this plugin along with TinyMCE to clean word pasted content.

 Since TinyMCE is now MIT licensed. Is it ok to replace the current LGPL license with MIT? Will much appreciate it. 

TinyMCE license update: (https://github.com/tinymce/tinymce/pull/7647 )

**Comment by avigoldman** [comment]
+1 on this. Any chance we could update the licence on this?
